### ISSUE TITLE
miniproject 설명 수정

### ISSUE THREAD

**Issue by Losecow** [cowcastle/cowcastle.github.io#10]
조금 더 매끄럽게 글이 읽혔으면 좋겠어!

**Comment by qlswltjdhandong** [comment]
어떤 부분이 잘 안 읽혀?

**Comment by qlswltjdhandong** [comment]
음 방금 바꾼거대로 하면 더 잘 읽히는 거 같아
회사에서 직원들의 출퇴근 시간을 관리하기 위한 시스템을 이번 miniproject를 통해 구현해보고자 함
이대로 그대로 설명에 적자
