### ISSUE TITLE
어떤 사진을 넣으면 좋을까?

### ISSUE THREAD

**Issue by qlswltjdhandong** [cowcastle/cowcastle.github.io#4]

**Comment by qlswltjdhandong** [comment]
![meeting-594091_1920](https://user-images.githubusercontent.com/104507267/166093445-d80ed757-66ac-4cb4-ada7-1e8856763257.jpg)

**Comment by qlswltjdhandong** [comment]
난 이거 괜찮은 거 같아!!

**Comment by qlswltjdhandong** [comment]
근데 출퇴근 이니깐 뭔가 문 여는 느낌의 사진이 더 좋을까?

**Comment by qlswltjdhandong** [comment]
![door-1845682_1920](https://user-images.githubusercontent.com/104507267/166185927-44a13f2c-aa1c-4cac-b6ef-f1ac15de2962.png)

**Comment by qlswltjdhandong** [comment]
이거 괜찮아?

**Comment by Losecow** [comment]
오 이거 괜찮다 나중에 보고 더 좋은 사진 있으면 수정하는거로 하고 먼저 넣어놓자!

**Comment by qlswltjdhandong** [comment]
ㅇㅋㅇㅋ
