### ISSUE TITLE
mini project 가 가지고 있는 대략적인 기능 설명

### ISSUE THREAD

**Issue by qlswltjdhandong** [cowcastle/cowcastle.github.io#7]

**Comment by qlswltjdhandong** [comment]
우리가 만든 함수들을 정리해서 넣으면 될 거 같아

**Comment by qlswltjdhandong** [comment]
만든 함수가 10개가 넘긴 한데 그거를 다 적기보다는 다른 함수에 쓰이는 함수는 제외하고 적으면 좋을 거 같아

**Comment by qlswltjdhandong** [comment]
예를 시간을 나타내는 함수를 다른 함수에서 쓰잖아 그래서 그거는 따로 시간을 나타냄 이렇게 나타내지 말자는 거지!!

**Comment by qlswltjdhandong** [comment]
사람 정보 추가
사람 정보 삭제
사람 정보 수정
이런 느낌으로 적는 거 어때?

**Comment by Losecow** [comment]
아하 !! 좋은 생각이다 그게 더 보기 편하고 간편해서 좋을거같아
