### ISSUE TITLE
제목 변경 관련 issue

### ISSUE THREAD

**Issue by Losecow** [cowcastle/cowcastle.github.io#8]
메인으로 맨 위에 떠 있는 - > cowcastleminiproject1 
이거를 좀 더 세련되고 멋있는 이름으로 바꿔보고싶은데 혹시 추천하는게 있을까?

**Comment by Losecow** [comment]
나는 SRCC 이거를 볼드체로 넣었으면 좋겠어

**Comment by qlswltjdhandong** [comment]
어 좋은 거 같아 그걸로 가자 ㄱ ㄱ

**Comment by qlswltjdhandong** [comment]
cowcastleminiproject1 이 부분을 SRCC로 적자는 거지?

**Comment by Losecow** [comment]
예아~~~
